service: sls-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221,
  region: eu-west-2

package:
  exclude:
    - layer/**
    - data/**

functions:
  createPdf:
    handler: handler.createPdf
    timeout: 30
    memorySize: 2048
    events:
      - http:
          method: GET
          path: /screenshot
          contentHandling: CONVERT_TO_BINARY